title: Mohammad Al Muktabar # your name (or website title) here
logo: "/images/Foto.JPG?raw=true" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  Recent graduate from Institut Teknologi Sumatera, with a degree in Informatics Engineering.

  <br><br>
  <a href="/pdf/CV_Mohammad Al Muktabar.pdf" target="_blank">View My CV (Curriculum Vitae)</a>
  <br>
  <a href="https://www.linkedin.com/in/mohammad-al-muktabar-32a4a72a4" target="_blank">View My LinkedIn Profile</a>
  <br>
  <a href="https://github.com/almuktabarr" target="_blank">View My Github</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
