title: Mohammad Al Muktabar # your name (or website title) here
logo: "/images/Foto.jpg" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  Fresh Graduate from Institut Teknologi Sumatera, majoring in Informatics Engineering. I am passionate about technology and always eager to learn new things. I have a strong interest in data science and machine learning.
  <br><br>

  <br><br>
  <a href="https://www.linkedin.com/in/mohammad-al-muktabar-32a4a72a4">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
